# Generated by Django 5.1.4 on 2024-12-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('health', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_action', models.CharField(choices=[('attack', 'Attack'), ('defend', 'Defend')], max_length=10)),
                ('enemy_part', models.CharField(choices=[('head', 'Head'), ('body', 'Body'), ('legs', 'Legs')], max_length=10)),
                ('player_action', models.CharField(choices=[('attack', 'Attack'), ('defend', 'Defend')], max_length=10)),
                ('player_part', models.CharField(choices=[('head', 'Head'), ('body', 'Body'), ('legs', 'Legs')], max_length=10)),
                ('result', models.CharField(choices=[('win', 'Win'), ('defeat', 'Defeat'), ('draw', 'Draw')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infinity.hero')),
            ],
        ),
    ]
