# Generated by Django 5.1.4 on 2024-12-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='enemy_part',
            field=models.CharField(choices=[('head', 'Head'), ('torso', 'Torso'), ('legs', 'Legs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_part',
            field=models.CharField(choices=[('head', 'Head'), ('torso', 'Torso'), ('legs', 'Legs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(choices=[('win', 'Win'), ('defeat', 'Defeat'), ('draw', 'Draw'), ('a_vs_a', 'A_vs_a'), ('a_vs_b', 'A_vs_b')], max_length=10),
        ),
    ]
