# Generated by Django 5.1.4 on 2024-12-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0003_remove_gamesession_player_gamesession_player_hp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='enemy_hp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_scores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='enemy_action',
            field=models.CharField(choices=[('атака', 'Attack'), ('защита', 'Defend')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='enemy_part',
            field=models.CharField(choices=[('голова', 'Head'), ('торс', 'Torso'), ('ноги', 'Legs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_action',
            field=models.CharField(choices=[('атака', 'Attack'), ('защита', 'Defend')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_part',
            field=models.CharField(choices=[('голова', 'Head'), ('торс', 'Torso'), ('ноги', 'Legs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(choices=[('Урон врагу', 'ap_vs_e'), ('Урон вам', 'ae_vs_p'), ('Вы блокируете', 'bp_vs_e'), ('Враг блокирует', 'be_vs_p'), ('урон друг другу', 'ap_vs_ae'), ('вы и враг блок', 'be_vs_bp')], max_length=20),
        ),
    ]
