# Generated by Django 5.1.4 on 2024-12-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='enemy_action',
            new_name='enemy_attack',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='enemy_part',
            new_name='enemy_def',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='player_action',
            new_name='player_attack',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='player_part',
            new_name='player_def',
        ),
    ]
