# Generated by Django 5.1.4 on 2024-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinity', '0006_rename_enemy_action_gamesession_enemy_attack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='enemy_attack',
            field=models.CharField(choices=[('голова', 'Head'), ('торс', 'Torso'), ('ноги', 'Legs')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='player_attack',
            field=models.CharField(choices=[('голова', 'Head'), ('торс', 'Torso'), ('ноги', 'Legs')], max_length=10),
        ),
    ]
